syntax = "proto3";

option csharp_namespace = "TIKSN.Licensing";

message LicenseParty {
  string email = 1;
  string website = 2;

  oneof party_kind {
    LicenseIndividualParty individual_party = 3;
    LicenseOrganizationParty organization_party = 4;
  }
}

message LicenseIndividualParty {
  string first_name = 1;
  string last_name = 2;
  string full_name = 3;
}

message LicenseOrganizationParty {
  string short_name = 1;
  string long_name = 2;
}

message LicenseMessage {
  bytes discriminator = 1;
  bytes serial_number = 2;
  LicenseParty licensor = 3;
  LicenseParty licensee = 4;
  int64 not_before = 5;
  int64 not_after = 6;
  optional bytes entitlements = 7;
}

message LicenseEnvelope {
  LicenseMessage message = 1;
  string signature_algorithm = 2;
  bytes signature = 3;
}
