# release-drafter automatically creates a draft release for you each time you complete a PR in the main branch.
# It uses GitHub labels to categorize changes (See categories) and draft the release.
# release-drafter also generates a version for your release based on GitHub labels. You can add a label of 'major',
# 'minor' or 'patch' to determine which number in the version to increment.
# You may need to add these labels yourself.
# See https://github.com/release-drafter/release-drafter
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"
no-changes-template: "- No changes"
categories:
  - title: "📚 Documentation"
    when:
      labels:
        - "documentation"
  - title: "🚀 New Features"
    when:
      labels:
        - "enhancement"
  - title: "🐛 Bug Fixes"
    when:
      labels:
        - "bug"
  - title: "🧰 Maintenance"
    when:
      labels:
        - "maintenance"
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - "major"
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - "minor"
  - type: version-resolver
    semver-increment: patch
    when:
      labels:
        - "patch"
version-resolver:
  default: patch
template: |
  $CHANGES

  ## 👨🏼‍💻 Contributors

  $CONTRIBUTORS
autolabeler:
  - label: "documentation"
    files:
      - "**/*.md"
  - label: "enhancement"
    files:
      - "TIKSN.Framework.Core/**/*"
      - "TIKSN.Framework.Maui/**/*"
      - "TIKSN.LanguageLocalization/**/*"
      - "TIKSN.RegionLocalization/**/*"
  - label: "maintenance"
    files:
      - ".github/**/*"
      - "TIKSN.Framework.Core.Tests/**/*"
      - "TIKSN.Framework.IntegrationTests/**/*"
      - "examples/**/*"
      - "*.ps1"
