//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIKSN.Finance.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIKSN.Finance.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ISO_4217 Pblshd=&quot;2015-01-01&quot;&gt;
        ///	&lt;CcyTbl&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;AFGHANISTAN&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Afghani&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;AFN&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;971&lt;/CcyNbr&gt;
        ///			&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///		&lt;/CcyNtry&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;ÅLAND ISLANDS&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Euro&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;EUR&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;978&lt;/CcyNbr&gt;
        ///			&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///		&lt;/CcyNtry&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;ALBANIA&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Lek&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;ALL&lt;/Ccy&gt;
        ///			&lt;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string table_a1 {
            get {
                return ResourceManager.GetString("table_a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ISO_4217 Pblshd=&quot;2015-01-01&quot;&gt;
        ///	&lt;HstrcCcyTbl&gt;
        ///		&lt;HstrcCcyNtry&gt;
        ///			&lt;CtryNm&gt;AFGHANISTAN&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Afghani&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;AFA&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;004&lt;/CcyNbr&gt;
        ///			&lt;WthdrwlDt&gt;2003-01&lt;/WthdrwlDt&gt;
        ///		&lt;/HstrcCcyNtry&gt;
        ///		&lt;HstrcCcyNtry&gt;
        ///			&lt;CtryNm&gt;ÅLAND ISLANDS&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Markka&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;FIM&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;246&lt;/CcyNbr&gt;
        ///			&lt;WthdrwlDt&gt;2002-03&lt;/WthdrwlDt&gt;
        ///		&lt;/HstrcCcyNtry&gt;
        ///		&lt;HstrcCcyNtry&gt;
        ///			&lt;CtryNm&gt;ALBANIA&lt;/CtryNm&gt;
        ///			&lt;Ccy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string table_a3 {
            get {
                return ResourceManager.GetString("table_a3", resourceCulture);
            }
        }
    }
}
