# zizmor: ignore[dangerous-triggers]
name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions: read-all

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Draft Release"
        uses: release-drafter/release-drafter@c345907820e0396f6f44bcfd9ac4763325f8feb0 # v7.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
